# Raúl Camilo Martín Bernal

In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 15

<b>1.</b> Importar el Data Set “Resultados Saber Pro Competencias Especificas 2018-2” de Datos Abiertos

In [2]:
df=pd.read_csv('Resultados_Saber_Pro_Competencias_Especificas_2018-2.csv')
df

,ESTU_CONSECUTIVO,RESULT_CODIGOPRUEBA,RESULT_NOMBREPRUEBA,RESULT_PUNTAJE,RESULT_DESEMPENO
0,EK201830010858,9003,PENSAMIENTO CIENTÍFICO - MATEMÁTICAS Y ESTADÍS...,168,3
1,EK201830004053,9003,PENSAMIENTO CIENTÍFICO - MATEMÁTICAS Y ESTADÍS...,165,3
2,EK201830018583,5002,FORMULACIÓN DE PROYECTOS DE INGENIERÍA,160,3
3,EK201830018583,9003,PENSAMIENTO CIENTÍFICO - MATEMÁTICAS Y ESTADÍS...,189,3
4,EK201830009467,5002,FORMULACIÓN DE PROYECTOS DE INGENIERÍA,157,3
5,EK201830009467,8003,PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS,173,3
6,EK201830008840,4003,INVESTIGACIÓN EN CIENCIAS SOCIALES,192,3
...,...,...,...,...,...
375276,EK201830243072,5002,FORMULACIÓN DE PROYECTOS DE INGENIERÍA,179,3
375277,EK201830243072,8003,PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS,191,3
375278,EK201830071983,2611,DISEÑO DE SISTEMAS PRODUCTIVOS Y LOGÍSTICOS,126,2
375279,EK201830071983,5002,FORMULACIÓN DE PROYECTOS DE INGENIERÍA,143,2
375280,EK201830071983,9003,PENSAMIENTO CIENTÍFICO - MATEMÁTICAS Y ESTADÍS...,128,2
375281,EK201830243073,5002,FORMULACIÓN DE PROYECTOS DE INGENIERÍA,159,3
375282,EK201830243073,8003,PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS,171,3

<b>2.</b> Imprimir los consecutivos de los estudiantes que en la prueba de GESTIÓN
FINANCIERA obtuvieron un DESEMPEÑO superior a 2

In [3]:
df['ESTU_CONSECUTIVO'][(df['RESULT_NOMBREPRUEBA'] == 'GESTIÓN FINANCIERA') & (df['RESULT_DESEMPENO'] >2)]

26        EK201830001912
114       EK201830015006
117       EK201830017424
262       EK201830016374
271       EK201830014972
347       EK201830034551
364       EK201830050353
               ...
375236    EK201830034700
375238    EK201830226711
375242    EK201830231861
375248    EK201830243065
375262    EK201830101141
375263    EK201830101139
375264    EK201830101129
Name: ESTU_CONSECUTIVO, Length: 19652, dtype: object

<b>3.</b> Imprimir los CONSECUTIVOS de los estudiantes que en la prueba de FORMULACIÓN
DE PROYECTOS DE INGENIERÍA obtuvieron un PUNTAJE inferior a 170

In [4]:
df['ESTU_CONSECUTIVO'][(df['RESULT_NOMBREPRUEBA'] == 'FORMULACIÓN DE PROYECTOS DE INGENIERÍA') & (df['RESULT_PUNTAJE'] < 170)]

2         EK201830018583
4         EK201830009467
7         EK201830001985
11        EK201830001957
17        EK201830017518
21        EK201830013940
28        EK201830004029
               ...
375221    EK201830234709
375226    EK201830243061
375233    EK201830031043
375267    EK201830142065
375269    EK201830243070
375279    EK201830071983
375281    EK201830243073
Name: ESTU_CONSECUTIVO, Length: 34182, dtype: object

<b>4.</b> Imprima los CONSECUTIVOS de los estudiantes y el NOMBRE DE LA PRUEBA donde
el PUNTAJE sea superior a 200

In [5]:
df[['ESTU_CONSECUTIVO','RESULT_NOMBREPRUEBA']][df['RESULT_PUNTAJE'] > 200]

       ESTU_CONSECUTIVO                                RESULT_NOMBREPRUEBA
18       EK201830017518          PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS
38       EK201830002129             FORMULACIÓN DE PROYECTOS DE INGENIERÍA
51       EK201830012170          PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS
56       EK201830002363                                            EVALUAR
57       EK201830002363                                             FORMAR
63       EK201830002762                                             FORMAR
65       EK201830002337                                            EVALUAR
...                 ...                                                ...
375152   EK201830146775                                  ATENCIÓN EN SALUD
375154   EK201830241208                             INVESTIGACIÓN JURÍDICA
375155   EK201830241210                             INVESTIGACIÓN JURÍDICA
375159   EK201830241331                                 GESTIÓN FINANCIERA
375173   EK201830232888                                             FORMAR
375190   EK201830146233                                            EVALUAR
375202   EK201830164563  PROMOCIÓN DE LA SALUD Y PREVENCIÓN DE LA ENFER...

[15937 rows x 2 columns]

<b>5.</b> Imprima el NOMBRE DE LAS PRUEBAS que obtuvieron DESEMPEÑO superior a 3.
Ojo el nombre de las pruebas no puede estar repetido

In [6]:
#sacando valores unicos y los muestra como una serie en este caso
pd.Series((df['RESULT_NOMBREPRUEBA'][df['RESULT_DESEMPENO'] >3]).unique())

0             PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS
1                FORMULACIÓN DE PROYECTOS DE INGENIERÍA
2                                               ENSEÑAR
3                                               EVALUAR
4                                                FORMAR
5          PENSAMIENTO CIENTÍFICO - CIENCIAS BIOLÓGICAS
6                         DISEÑO DE SISTEMAS DE CONTROL
                            ...
18                   INVESTIGACIÓN EN CIENCIAS SOCIALES
19                                   ANÁLISIS ECONÓMICO
20                      DISEÑO DE PROCESOS INDUSTRIALES
21    FUNDAMENTACIÓN EN DIAGNÓSTICO Y TRATAMIENTO MÉ...
22                                  PRODUCCIÓN PECUARIA
23       PENSAMIENTO CIENTÍFICO - CIENCIAS DE LA TIERRA
24                    INTERVENCIÓN EN PROCESOS SOCIALES
Length: 25, dtype: object

<b>6.</b> Utilizando WHERE convierta en NaN todos los registros donde el PUNTAJE no sea
superior a 170 y luego elimine esos registros

In [7]:
df2=df
filtro=df2['RESULT_PUNTAJE']>170
df2=df2.where(filtro,np.nan)
df2=df2.dropna(axis=0, how='all')
df2

,ESTU_CONSECUTIVO,RESULT_CODIGOPRUEBA,RESULT_NOMBREPRUEBA,RESULT_PUNTAJE,RESULT_DESEMPENO
3,EK201830018583,9003.0,PENSAMIENTO CIENTÍFICO - MATEMÁTICAS Y ESTADÍS...,189.0,3.0
5,EK201830009467,8003.0,PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS,173.0,3.0
6,EK201830008840,4003.0,INVESTIGACIÓN EN CIENCIAS SOCIALES,192.0,3.0
13,EK201830004765,5002.0,FORMULACIÓN DE PROYECTOS DE INGENIERÍA,189.0,3.0
15,EK201830011121,9003.0,PENSAMIENTO CIENTÍFICO - MATEMÁTICAS Y ESTADÍS...,187.0,3.0
18,EK201830017518,8003.0,PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS,206.0,4.0
23,EK201830005585,8002.0,GESTIÓN DE ORGANIZACIONES,197.0,3.0
...,...,...,...,...,...
375253,EK201830243067,8002.0,GESTIÓN DE ORGANIZACIONES,177.0,3.0
375262,EK201830101141,1003.0,GESTIÓN FINANCIERA,171.0,3.0
375270,EK201830243070,8003.0,PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS,195.0,3.0
375275,EK201830243072,9001.0,DISEÑO DE SISTEMAS DE CONTROL,173.0,3.0
375276,EK201830243072,5002.0,FORMULACIÓN DE PROYECTOS DE INGENIERÍA,179.0,3.0
375277,EK201830243072,8003.0,PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS,191.0,3.0
375282,EK201830243073,8003.0,PENSAMIENTO CIENTÍFICO - CIENCIAS FÍSICAS,171.0,3.0

<b>7.</b> Utilizando MASK convierta en NaN todos los registros donde el DESEMPEÑO no sea
inferior a 3 y luego elimine esos registros.

In [10]:
df3=df
mask=df3['RESULT_DESEMPENO'] >= 3
df3=df3.mask(mask,np.nan)
df3=df3.dropna(axis=0, how='all')
df3

,ESTU_CONSECUTIVO,RESULT_CODIGOPRUEBA,RESULT_NOMBREPRUEBA,RESULT_PUNTAJE,RESULT_DESEMPENO
8,EK201830001985,6003.0,PENSAMIENTO CIENTÍFICO - CIENCIAS BIOLÓGICAS,153.0,2.0
9,EK201830012355,8002.0,GESTIÓN DE ORGANIZACIONES,132.0,2.0
10,EK201830012355,1003.0,GESTIÓN FINANCIERA,141.0,2.0
12,EK201830001957,6003.0,PENSAMIENTO CIENTÍFICO - CIENCIAS BIOLÓGICAS,144.0,2.0
16,EK201830012433,4005.0,INVESTIGACIÓN JURÍDICA,142.0,2.0
19,EK201830017369,8002.0,GESTIÓN DE ORGANIZACIONES,145.0,2.0
20,EK201830017369,1003.0,GESTIÓN FINANCIERA,125.0,1.0
...,...,...,...,...,...
375269,EK201830243070,5002.0,FORMULACIÓN DE PROYECTOS DE INGENIERÍA,130.0,1.0
375271,EK201830109051,1003.0,GESTIÓN FINANCIERA,130.0,1.0
375272,EK201830103679,1004.0,PENSAMIENTO CIENTÍFICO - QUÍMICA,147.0,2.0
375273,EK201830223658,4001.0,ATENCIÓN EN SALUD,140.0,2.0
375278,EK201830071983,2611.0,DISEÑO DE SISTEMAS PRODUCTIVOS Y LOGÍSTICOS,126.0,2.0
375279,EK201830071983,5002.0,FORMULACIÓN DE PROYECTOS DE INGENIERÍA,143.0,2.0
375280,EK201830071983,9003.0,PENSAMIENTO CIENTÍFICO - MATEMÁTICAS Y ESTADÍS...,128.0,2.0

<b>8.</b> Utilizando Isin imprima los CONSECUTIVOS de los estudiantes y el NOMBRE
DE LA PRUEBA donde el PUNTAJE sea 160 o 170 o 180 o 190 o 200.

In [11]:
dfisin=df['RESULT_PUNTAJE'].isin([160,170,180,190,200])
df[['ESTU_CONSECUTIVO','RESULT_NOMBREPRUEBA']][dfisin]

       ESTU_CONSECUTIVO                           RESULT_NOMBREPRUEBA
2        EK201830018583        FORMULACIÓN DE PROYECTOS DE INGENIERÍA
37       EK201830019303              PENSAMIENTO CIENTÍFICO - QUÍMICA
39       EK201830002129  PENSAMIENTO CIENTÍFICO - CIENCIAS BIOLÓGICAS
43       EK201830020199        FORMULACIÓN DE PROYECTOS DE INGENIERÍA
46       EK201830005887                                       EVALUAR
67       EK201830012539        FORMULACIÓN DE PROYECTOS DE INGENIERÍA
87       EK201830017724                                       EVALUAR
...                 ...                                           ...
375063   EK201830169498                                        FORMAR
375138   EK201830171897                                       ENSEÑAR
375185   EK201830146463                                       EVALUAR
375192   EK201830146176                                       ENSEÑAR
375194   EK201830146176                                        FORMAR
375201   EK201830164563                             ATENCIÓN EN SALUD
375238   EK201830226711                            GESTIÓN FINANCIERA

[13515 rows x 2 columns]